### PR TITLE
performance improvements

### PR DESCRIPTION
**Pull request by arnaudNYC**
This PR includes the following changes:

- Favor rest parameters over the use `arguments`
- Remove the use of hasOwnProperty for slight performance improvement
- Replace the for...of by a forEach as it does not transpile well to ES5
- Bump up node minimum version to 5
- Bump up version of ava to remove low security warning
- A slight performance improvement (~15% for 1M elements) can be observed

### CODE REVIEW

**Comment by nikitaeverywhere** [comment]
Hello Arnaud!

Thank you very much!

Is there any evidence that this indeed improves performance?

**Comment by arnaudNYC** [comment]
Thanks for getting back to me! It's really minimal, mostly due (I suspect) to how node processes the code now compared to how it was written then. I'm going to write a small benchmark to corroborate/debunk my claim, I hope to have it in the next day or two. Have a great weekend!

**Comment by nikitaeverywhere** [comment]
Thank you! That would be really great.

Personally, I would avoid dropping older node versions if there are no
significant changes in performance.

**Comment by arnaudNYC** [comment]
I wrote a benchmark (https://github.com/arnaudNYC/array-merge-by-key/tree/benchmark) and ran it, and the two solutions were equivalent. I then restored the check using hasOwnProperty to remain identical to the original intent, and your original solution was faster 10 out of 10 times! So thanks for keeping me honest here.

I was also mistaken about the claim on for...of not transpiling well to ES5, I had it mixed up with generators (https://github.com/airbnb/javascript#generators--nope), so that's fine too.

The `arguments` replacement is because of this lint rule: https://eslint.org/docs/rules/prefer-rest-params, but it really doesn't change anything.

The last change that has some (relative) value is the upgrade of ava. Should you want to resolve that warning, the changes in this PR will work.

Well done on writing time resistant code!

Best,
Arnaud

**Comment by nikitaeverywhere** [comment]
Thank you @arnaudNYC! Glad you've tested it. A little story behind at least `arguments` - some code decisions here were made intentionally for performance reasons and that's why I was wondering :) If you would like to make a PR updating dependencies like Ava you are very welcome! But anyway they are dev dependencies and does not affect package users anyhow.

**Pull request closed without merging**
